---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pinvsearch

<!-- badges: start -->
<!-- badges: end -->

The goal of pinvsearch is to automate the process of performing specification search in identifying noninvariant items to arrive at a partial factorial invariance model. 

## Installation

<!-- You can install the released version of pinvsearch from [CRAN](https://CRAN.R-project.org) with: -->

<!-- ``` r -->
<!-- install.packages("pinvsearch") -->
<!-- ``` -->

<!-- And the development version from [GitHub](https://github.com/) with: -->

You can install the development version of pinvsearch from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("marklhc/pinvsearch")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(pinvsearch)
library(lavaan)
HS.model <- '  visual =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '
# Output the final partial invariance model, and the noninvariant items
pinvSearch(HS.model, data = HolzingerSwineford1939, 
           group = "school", type = "intercepts")
```
